name: hedon_viewer
description: "Hedon haven"
publish_to: 'none'
version: 0.5.4+2203
environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  html: ^0.15.6
  shared_preferences: ^2.5.4
  fvp: ^0.35.2
  video_player: ^2.10.1
  audio_video_progress_bar: ^2.0.3
  auto_orientation: #^2.3.1
    git: https://github.com/Kanwarpalsingh1986/auto_orientation
  window_manager: ^0.5.1
  flutter_hls_parser: ^2.0.1
  url_launcher: ^6.3.2
  dynamic_color: ^1.8.1
  wakelock_plus: ^1.4.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  skeletonizer: ^2.1.2
  sqflite_common_ffi: ^2.4.0+2
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  toastification: ^3.0.3
  system_info2: ^4.1.0
  apk_installer: ^0.0.4
  dynamic_app_icon_flutter: #^0.0.3
    git: https://github.com/Hedon-dev/dynamic_app_icon
  yaml: ^3.1.3
  logger: ^2.6.2
  archive: ^4.0.7
  file_picker: ^10.3.10
  image: ^4.7.2
  crypto: ^3.0.7
  share_plus: ^12.0.1
  html_unescape: ^2.0.0
  linkify: ^5.0.0
  secure_app_switcher: ^1.0.0
  page_transition: ^2.2.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.20.2
  flutter_js: ^0.8.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.0


flutter:
  uses-material-design: true
  assets:
    - assets/launcher-icon/stock.png
    - assets/launcher-icon/fake_settings.png
    - assets/launcher-icon/reminders.png
